#!/bin/bash

set -e

git_status

NAME="$@"
master="$(git_default_branch)"

BRANCH=`git_safe_name "$NAME"`

git fetch origin $master
git checkout origin/$master
git checkout -b $BRANCH

git commit --allow-empty -m "$NAME"
