#!/bin/bash

set -e

PROJECT="$(gcloud projects list | grep -v PROJECT_ID | fzf | awk '{print $1}')"

CLUSTERS="$(gcloud --project $PROJECT container clusters list | grep RUNNING)"

CLUSTER="$(echo "$CLUSTERS" | awk '{print $1}' | fzf)"

ZONE="$(echo "$CLUSTERS" | grep "^$CLUSTER" | head -n 1 | awk '{print $2}')"

gcloud --project $PROJECT container clusters get-credentials $CLUSTER --zone $ZONE

NAMESPACE="$(kubectl get namespace | grep Active | awk '{print $1}' | fzf)"

echo "k8s context: $PROJECT / $CLUSTER / $NAMESPACE"

kubectl config set-context $(kubectl config current-context) --namespace=$NAMESPACE

kubectl config get-contexts $(kubectl config current-context)
