#!/bin/bash

set -e

PROJECT="$1"

if [ -z "$PROJECT" ] ; then
    PROJECT="$(gcloud projects list | grep -v PROJECT_ID | fzf | awk '{print $1}')"
fi

CLUSTERS="$(gcloud --project "$PROJECT" container clusters list 2> /dev/null | grep RUNNING)"

CLUSTER="$(echo "$CLUSTERS" | awk '{print $1}' | fzf)"

ZONE="$(echo "$CLUSTERS" | grep -m 1 "^$CLUSTER " | awk '{print $2}')"

gcloud --project "$PROJECT" container clusters get-credentials $CLUSTER --zone $ZONE

k8s_current
